
FROM node:alpine3.11

# Install Shadow non busybox for better user management & support
RUN apk add --no-cache shadow git

# Add Sudo to allow occasional usage of root. I wish I could remove this but I can't seem to get the node_modules volume working correctly.
RUN apk add --no-cache sudo \
  && echo node ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/node \
  && chmod 0440 /etc/sudoers.d/node


CMD [ "tail", "-f", "/dev/null" ]